run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - misspell
    - gosimple
    - gocritic

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - ifElseChain
      - hugeParam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocritic
        - errcheck
