create table if not exists public.photo (
  id bigint generated by default as identity not null,
  post_id bigint not null,
  s3_key text not null,
  position integer not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  constraint photo_pkey primary key (id),
  constraint photo_post_id_fkey
    foreign key (post_id)
    references public.post (id)
    on update cascade
    on delete cascade,
  constraint photo_position_nonnegative check (position >= 0),
  constraint photo_s3_key_not_blank check (length(trim(s3_key)) > 0),
  constraint photo_post_position_key unique (post_id, position),
  constraint photo_post_s3_key_key unique (post_id, s3_key)
);

create index if not exists photo_post_id_position_idx
  on public.photo using btree (post_id, position);

create trigger trg_photo_set_updated_at
before update on public.photo
for each row
execute function set_updated_at();
