create extension if not exists "citext" with schema "extensions";

drop extension if exists "pg_net";

create schema if not exists "app_private";

create schema if not exists "staging_digitalocean_supost";

create sequence "staging_digitalocean_supost"."message_staging_import_id_seq";

create sequence "staging_digitalocean_supost"."post_staging_import_id_seq";


  create table "app_private"."account" (
    "id" bigint generated by default as identity not null,
    "email" extensions.citext not null,
    "status" text not null default 'unverified'::text,
    "access_token" text not null,
    "original_login_ip" inet,
    "last_login_ip" inet,
    "current_login_ip" inet,
    "total_message_count" integer not null default 0,
    "current_message_count" integer not null default 0,
    "current_message_date" date not null,
    "verified_at" timestamp with time zone,
    "verification_count" integer not null default 0,
    "last_verification_sent_at" timestamp with time zone,
    "next_verification_sent_at" timestamp with time zone,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone
      );



  create table "app_private"."message" (
    "id" bigint generated by default as identity not null,
    "message" text,
    "post_id" bigint,
    "ip" inet,
    "email" extensions.citext not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone,
    "source" text default 'other'::text,
    "status" text default 'queued'::text,
    "raw_email" extensions.citext not null,
    "user_agent" text,
    "account_id" bigint,
    "scammed" boolean default false
      );



  create table "app_private"."message_scam_rule" (
    "id" bigint generated by default as identity not null,
    "rule" text,
    "content" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone,
    "field_name" text default 'message'::text
      );



  create table "app_private"."scammer" (
    "id" bigint generated by default as identity not null,
    "email" extensions.citext not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone
      );



  create table "app_private"."spammer" (
    "id" bigint generated by default as identity not null,
    "email" extensions.citext not null,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone
      );



  create table "public"."category" (
    "id" bigint generated by default as identity not null,
    "name" text,
    "short_name" text
      );



  create table "public"."post" (
    "id" bigint generated by default as identity not null,
    "college_id" integer,
    "category_id" bigint,
    "subcategory_id" bigint,
    "email" extensions.citext not null,
    "ip" inet,
    "name" text,
    "body" text,
    "security_id" integer,
    "time_posted" integer,
    "time_modified" integer,
    "image_source1" text,
    "image_source2" text,
    "image_source3" text,
    "image_source4" text,
    "status" integer,
    "photo1_file_name" text,
    "photo1_content_type" text,
    "photo2_file_name" text,
    "photo2_content_type" text,
    "photo3_file_name" text,
    "photo3_content_type" text,
    "photo4_file_name" text,
    "photo4_content_type" text,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone,
    "access_token" text,
    "price" numeric(10,2),
    "enable_purchases" boolean not null default false,
    "rate" numeric(10,2) not null default 0.00,
    "fee" numeric(10,2) not null default 0.00,
    "premium" boolean not null default false,
    "spammed" boolean not null default false,
    "time_posted_at" timestamp with time zone,
    "time_modified_at" timestamp with time zone
      );


alter table "public"."post" enable row level security;


  create table "public"."subcategory" (
    "id" bigint generated by default as identity not null,
    "category_id" bigint,
    "name" text
      );



  create table "staging_digitalocean_supost"."message_staging_import" (
    "id" integer not null default nextval('staging_digitalocean_supost.message_staging_import_id_seq'::regclass),
    "message" text,
    "post_id" integer,
    "ip" character varying(20),
    "email" character varying(100) not null,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    "source" character varying(40) default 'other'::character varying,
    "status" character varying(40) default 'queued'::character varying,
    "raw_email" character varying(100) not null,
    "user_agent" text,
    "account_id" integer,
    "scammed" boolean default false
      );



  create table "staging_digitalocean_supost"."post_staging_import" (
    "id" integer not null default nextval('staging_digitalocean_supost.post_staging_import_id_seq'::regclass),
    "college_id" integer,
    "category_id" integer,
    "subcategory_id" integer,
    "email" character varying(100) not null,
    "ip" character varying(255),
    "name" character varying(255),
    "body" text,
    "security_id" integer,
    "time_posted" integer,
    "time_modified" integer,
    "image_source1" character varying(255),
    "image_source2" character varying(255),
    "image_source3" character varying(255),
    "image_source4" character varying(255),
    "status" integer,
    "photo1_file_name" character varying(255),
    "photo1_content_type" character varying(40),
    "photo2_file_name" character varying(255),
    "photo2_content_type" character varying(40),
    "photo3_file_name" character varying(255),
    "photo3_content_type" character varying(40),
    "photo4_file_name" character varying(255),
    "photo4_content_type" character varying(40),
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "access_token" character varying(255),
    "price" numeric(10,2),
    "enable_purchases" boolean default false,
    "rate" numeric(10,2) default 0.00,
    "fee" numeric(10,2) default 0.00,
    "premium" boolean default false,
    "spammed" boolean default false,
    "url_slug" text generated always as (('https://supost.com/post/index/'::text || (id)::text)) stored,
    "_dlt_load_id" text not null,
    "_dlt_id" text not null,
    "enable_purchases__v_bool" boolean,
    "premium__v_bool" boolean,
    "spammed__v_bool" boolean
      );



  create table "staging_digitalocean_supost"."post_staging_import_latest" (
    "id" integer generated by default as identity not null,
    "college_id" integer,
    "category_id" integer not null,
    "subcategory_id" integer not null,
    "email" character varying(100) not null,
    "ip" character varying(255),
    "name" character varying(255) not null,
    "body" text not null,
    "security_id" integer,
    "time_posted" integer not null,
    "time_modified" integer,
    "image_source1" character varying(255),
    "image_source2" character varying(255),
    "image_source3" character varying(255),
    "image_source4" character varying(255),
    "status" integer not null,
    "photo1_file_name" character varying(255),
    "photo1_content_type" character varying(40),
    "photo2_file_name" character varying(255),
    "photo2_content_type" character varying(40),
    "photo3_file_name" character varying(255),
    "photo3_content_type" character varying(40),
    "photo4_file_name" character varying(255),
    "photo4_content_type" character varying(40),
    "created_at" timestamp without time zone,
    "updated_at" timestamp without time zone,
    "access_token" character varying(255),
    "price" numeric(10,2),
    "enable_purchases" boolean default false,
    "rate" numeric(10,2) default 0.00,
    "fee" numeric(10,2) default 0.00,
    "premium" boolean default false,
    "spammed" boolean default false,
    "source_api_id" uuid
      );


alter sequence "staging_digitalocean_supost"."message_staging_import_id_seq" owned by "staging_digitalocean_supost"."message_staging_import"."id";

alter sequence "staging_digitalocean_supost"."post_staging_import_id_seq" owned by "staging_digitalocean_supost"."post_staging_import"."id";

CREATE UNIQUE INDEX account_access_token_key ON app_private.account USING btree (access_token);

CREATE UNIQUE INDEX account_email_key ON app_private.account USING btree (email);

CREATE UNIQUE INDEX account_pkey ON app_private.account USING btree (id);

CREATE INDEX message_account_id_idx ON app_private.message USING btree (account_id);

CREATE INDEX message_email_idx ON app_private.message USING btree (email);

CREATE UNIQUE INDEX message_pkey ON app_private.message USING btree (id);

CREATE INDEX message_post_id_idx ON app_private.message USING btree (post_id);

CREATE INDEX message_scam_rule_field_name_idx ON app_private.message_scam_rule USING btree (field_name);

CREATE UNIQUE INDEX message_scam_rule_pkey ON app_private.message_scam_rule USING btree (id);

CREATE INDEX message_scammed_idx ON app_private.message USING btree (scammed);

CREATE INDEX message_status_email_idx ON app_private.message USING btree (status, email);

CREATE UNIQUE INDEX scammer_email_key ON app_private.scammer USING btree (email);

CREATE UNIQUE INDEX scammer_pkey ON app_private.scammer USING btree (id);

CREATE UNIQUE INDEX spammer_email_key ON app_private.spammer USING btree (email);

CREATE UNIQUE INDEX spammer_pkey ON app_private.spammer USING btree (id);

CREATE UNIQUE INDEX category_pkey ON public.category USING btree (id);

CREATE INDEX idx_post_active_category_time_posted_desc ON public.post USING btree (category_id, time_posted DESC) WHERE (status = 1);

CREATE INDEX idx_post_active_photo_time_posted_desc ON public.post USING btree (time_posted DESC) WHERE ((status = 1) AND (((photo1_file_name IS NOT NULL) AND (photo1_file_name <> ''::text)) OR ((photo2_file_name IS NOT NULL) AND (photo2_file_name <> ''::text)) OR ((photo3_file_name IS NOT NULL) AND (photo3_file_name <> ''::text)) OR ((photo4_file_name IS NOT NULL) AND (photo4_file_name <> ''::text)) OR ((image_source1 IS NOT NULL) AND (image_source1 <> ''::text)) OR ((image_source2 IS NOT NULL) AND (image_source2 <> ''::text)) OR ((image_source3 IS NOT NULL) AND (image_source3 <> ''::text)) OR ((image_source4 IS NOT NULL) AND (image_source4 <> ''::text))));

CREATE INDEX idx_post_active_time_posted_desc ON public.post USING btree (time_posted DESC) WHERE (status = 1);

CREATE INDEX idx_post_status_category_time_posted_desc ON public.post USING btree (status, category_id, time_posted DESC);

CREATE UNIQUE INDEX post_access_token_key ON public.post USING btree (access_token);

CREATE INDEX post_category_id_status_idx ON public.post USING btree (category_id, status);

CREATE INDEX post_email_idx ON public.post USING btree (email);

CREATE UNIQUE INDEX post_pkey ON public.post USING btree (id);

CREATE INDEX post_premium_idx ON public.post USING btree (premium);

CREATE INDEX post_spammed_idx ON public.post USING btree (spammed);

CREATE INDEX post_status_email_idx ON public.post USING btree (status, email);

CREATE INDEX post_status_spammed_time_idx ON public.post USING btree (status, spammed, time_posted_at DESC NULLS LAST) WHERE ((status = 1) AND (spammed = false));

CREATE INDEX post_subcategory_id_status_idx ON public.post USING btree (subcategory_id, status);

CREATE INDEX post_time_modified_at_idx ON public.post USING btree (time_modified_at DESC);

CREATE INDEX post_time_posted_at_idx ON public.post USING btree (time_posted_at DESC);

CREATE INDEX subcategory_category_id_idx ON public.subcategory USING btree (category_id);

CREATE UNIQUE INDEX subcategory_pkey ON public.subcategory USING btree (id);

CREATE INDEX idx_message_staging_import_account_id ON staging_digitalocean_supost.message_staging_import USING btree (account_id);

CREATE INDEX idx_message_staging_import_email ON staging_digitalocean_supost.message_staging_import USING btree (email);

CREATE INDEX idx_message_staging_import_post_id ON staging_digitalocean_supost.message_staging_import USING btree (post_id);

CREATE INDEX idx_message_staging_import_scammed ON staging_digitalocean_supost.message_staging_import USING btree (scammed);

CREATE INDEX idx_message_staging_import_status_email ON staging_digitalocean_supost.message_staging_import USING btree (status, email);

CREATE UNIQUE INDEX message_staging_import_pkey ON staging_digitalocean_supost.message_staging_import USING btree (id);

CREATE UNIQUE INDEX post_staging_import_latest_pkey ON staging_digitalocean_supost.post_staging_import_latest USING btree (id);

alter table "app_private"."account" add constraint "account_pkey" PRIMARY KEY using index "account_pkey";

alter table "app_private"."message" add constraint "message_pkey" PRIMARY KEY using index "message_pkey";

alter table "app_private"."message_scam_rule" add constraint "message_scam_rule_pkey" PRIMARY KEY using index "message_scam_rule_pkey";

alter table "app_private"."scammer" add constraint "scammer_pkey" PRIMARY KEY using index "scammer_pkey";

alter table "app_private"."spammer" add constraint "spammer_pkey" PRIMARY KEY using index "spammer_pkey";

alter table "public"."category" add constraint "category_pkey" PRIMARY KEY using index "category_pkey";

alter table "public"."post" add constraint "post_pkey" PRIMARY KEY using index "post_pkey";

alter table "public"."subcategory" add constraint "subcategory_pkey" PRIMARY KEY using index "subcategory_pkey";

alter table "staging_digitalocean_supost"."message_staging_import" add constraint "message_staging_import_pkey" PRIMARY KEY using index "message_staging_import_pkey";

alter table "staging_digitalocean_supost"."post_staging_import_latest" add constraint "post_staging_import_latest_pkey" PRIMARY KEY using index "post_staging_import_latest_pkey";

alter table "app_private"."account" add constraint "account_current_message_count_nonnegative" CHECK ((current_message_count >= 0)) not valid;

alter table "app_private"."account" validate constraint "account_current_message_count_nonnegative";

alter table "app_private"."account" add constraint "account_total_message_count_nonnegative" CHECK ((total_message_count >= 0)) not valid;

alter table "app_private"."account" validate constraint "account_total_message_count_nonnegative";

alter table "app_private"."account" add constraint "account_verification_count_nonnegative" CHECK ((verification_count >= 0)) not valid;

alter table "app_private"."account" validate constraint "account_verification_count_nonnegative";

alter table "app_private"."message" add constraint "message_account_id_fkey" FOREIGN KEY (account_id) REFERENCES app_private.account(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID not valid;

alter table "app_private"."message" validate constraint "message_account_id_fkey";

alter table "app_private"."message" add constraint "message_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.post(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID not valid;

alter table "app_private"."message" validate constraint "message_post_id_fkey";

alter table "app_private"."scammer" add constraint "scammer_email_key" UNIQUE using index "scammer_email_key";

alter table "app_private"."spammer" add constraint "spammer_email_key" UNIQUE using index "spammer_email_key";

alter table "public"."subcategory" add constraint "subcategory_category_id_fkey" FOREIGN KEY (category_id) REFERENCES public.category(id) ON UPDATE CASCADE ON DELETE SET NULL NOT VALID not valid;

alter table "public"."subcategory" validate constraint "subcategory_category_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.set_updated_at()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
  new.updated_at = now();
  return new;
end;
$function$
;

grant delete on table "app_private"."account" to "anon";

grant insert on table "app_private"."account" to "anon";

grant references on table "app_private"."account" to "anon";

grant select on table "app_private"."account" to "anon";

grant trigger on table "app_private"."account" to "anon";

grant truncate on table "app_private"."account" to "anon";

grant update on table "app_private"."account" to "anon";

grant delete on table "app_private"."account" to "authenticated";

grant insert on table "app_private"."account" to "authenticated";

grant references on table "app_private"."account" to "authenticated";

grant select on table "app_private"."account" to "authenticated";

grant trigger on table "app_private"."account" to "authenticated";

grant truncate on table "app_private"."account" to "authenticated";

grant update on table "app_private"."account" to "authenticated";

grant delete on table "app_private"."account" to "service_role";

grant insert on table "app_private"."account" to "service_role";

grant references on table "app_private"."account" to "service_role";

grant select on table "app_private"."account" to "service_role";

grant trigger on table "app_private"."account" to "service_role";

grant truncate on table "app_private"."account" to "service_role";

grant update on table "app_private"."account" to "service_role";

grant delete on table "app_private"."message" to "anon";

grant insert on table "app_private"."message" to "anon";

grant references on table "app_private"."message" to "anon";

grant select on table "app_private"."message" to "anon";

grant trigger on table "app_private"."message" to "anon";

grant truncate on table "app_private"."message" to "anon";

grant update on table "app_private"."message" to "anon";

grant delete on table "app_private"."message" to "authenticated";

grant insert on table "app_private"."message" to "authenticated";

grant references on table "app_private"."message" to "authenticated";

grant select on table "app_private"."message" to "authenticated";

grant trigger on table "app_private"."message" to "authenticated";

grant truncate on table "app_private"."message" to "authenticated";

grant update on table "app_private"."message" to "authenticated";

grant delete on table "app_private"."message" to "service_role";

grant insert on table "app_private"."message" to "service_role";

grant references on table "app_private"."message" to "service_role";

grant select on table "app_private"."message" to "service_role";

grant trigger on table "app_private"."message" to "service_role";

grant truncate on table "app_private"."message" to "service_role";

grant update on table "app_private"."message" to "service_role";

grant delete on table "app_private"."message_scam_rule" to "anon";

grant insert on table "app_private"."message_scam_rule" to "anon";

grant references on table "app_private"."message_scam_rule" to "anon";

grant select on table "app_private"."message_scam_rule" to "anon";

grant trigger on table "app_private"."message_scam_rule" to "anon";

grant truncate on table "app_private"."message_scam_rule" to "anon";

grant update on table "app_private"."message_scam_rule" to "anon";

grant delete on table "app_private"."message_scam_rule" to "authenticated";

grant insert on table "app_private"."message_scam_rule" to "authenticated";

grant references on table "app_private"."message_scam_rule" to "authenticated";

grant select on table "app_private"."message_scam_rule" to "authenticated";

grant trigger on table "app_private"."message_scam_rule" to "authenticated";

grant truncate on table "app_private"."message_scam_rule" to "authenticated";

grant update on table "app_private"."message_scam_rule" to "authenticated";

grant delete on table "app_private"."message_scam_rule" to "service_role";

grant insert on table "app_private"."message_scam_rule" to "service_role";

grant references on table "app_private"."message_scam_rule" to "service_role";

grant select on table "app_private"."message_scam_rule" to "service_role";

grant trigger on table "app_private"."message_scam_rule" to "service_role";

grant truncate on table "app_private"."message_scam_rule" to "service_role";

grant update on table "app_private"."message_scam_rule" to "service_role";

grant delete on table "app_private"."scammer" to "anon";

grant insert on table "app_private"."scammer" to "anon";

grant references on table "app_private"."scammer" to "anon";

grant select on table "app_private"."scammer" to "anon";

grant trigger on table "app_private"."scammer" to "anon";

grant truncate on table "app_private"."scammer" to "anon";

grant update on table "app_private"."scammer" to "anon";

grant delete on table "app_private"."scammer" to "authenticated";

grant insert on table "app_private"."scammer" to "authenticated";

grant references on table "app_private"."scammer" to "authenticated";

grant select on table "app_private"."scammer" to "authenticated";

grant trigger on table "app_private"."scammer" to "authenticated";

grant truncate on table "app_private"."scammer" to "authenticated";

grant update on table "app_private"."scammer" to "authenticated";

grant delete on table "app_private"."scammer" to "service_role";

grant insert on table "app_private"."scammer" to "service_role";

grant references on table "app_private"."scammer" to "service_role";

grant select on table "app_private"."scammer" to "service_role";

grant trigger on table "app_private"."scammer" to "service_role";

grant truncate on table "app_private"."scammer" to "service_role";

grant update on table "app_private"."scammer" to "service_role";

grant delete on table "app_private"."spammer" to "anon";

grant insert on table "app_private"."spammer" to "anon";

grant references on table "app_private"."spammer" to "anon";

grant select on table "app_private"."spammer" to "anon";

grant trigger on table "app_private"."spammer" to "anon";

grant truncate on table "app_private"."spammer" to "anon";

grant update on table "app_private"."spammer" to "anon";

grant delete on table "app_private"."spammer" to "authenticated";

grant insert on table "app_private"."spammer" to "authenticated";

grant references on table "app_private"."spammer" to "authenticated";

grant select on table "app_private"."spammer" to "authenticated";

grant trigger on table "app_private"."spammer" to "authenticated";

grant truncate on table "app_private"."spammer" to "authenticated";

grant update on table "app_private"."spammer" to "authenticated";

grant delete on table "app_private"."spammer" to "service_role";

grant insert on table "app_private"."spammer" to "service_role";

grant references on table "app_private"."spammer" to "service_role";

grant select on table "app_private"."spammer" to "service_role";

grant trigger on table "app_private"."spammer" to "service_role";

grant truncate on table "app_private"."spammer" to "service_role";

grant update on table "app_private"."spammer" to "service_role";

grant delete on table "public"."category" to "anon";

grant insert on table "public"."category" to "anon";

grant references on table "public"."category" to "anon";

grant select on table "public"."category" to "anon";

grant trigger on table "public"."category" to "anon";

grant truncate on table "public"."category" to "anon";

grant update on table "public"."category" to "anon";

grant delete on table "public"."category" to "authenticated";

grant insert on table "public"."category" to "authenticated";

grant references on table "public"."category" to "authenticated";

grant select on table "public"."category" to "authenticated";

grant trigger on table "public"."category" to "authenticated";

grant truncate on table "public"."category" to "authenticated";

grant update on table "public"."category" to "authenticated";

grant delete on table "public"."category" to "service_role";

grant insert on table "public"."category" to "service_role";

grant references on table "public"."category" to "service_role";

grant select on table "public"."category" to "service_role";

grant trigger on table "public"."category" to "service_role";

grant truncate on table "public"."category" to "service_role";

grant update on table "public"."category" to "service_role";

grant delete on table "public"."post" to "anon";

grant insert on table "public"."post" to "anon";

grant references on table "public"."post" to "anon";

grant select on table "public"."post" to "anon";

grant trigger on table "public"."post" to "anon";

grant truncate on table "public"."post" to "anon";

grant update on table "public"."post" to "anon";

grant delete on table "public"."post" to "authenticated";

grant insert on table "public"."post" to "authenticated";

grant references on table "public"."post" to "authenticated";

grant trigger on table "public"."post" to "authenticated";

grant truncate on table "public"."post" to "authenticated";

grant update on table "public"."post" to "authenticated";

grant delete on table "public"."post" to "service_role";

grant insert on table "public"."post" to "service_role";

grant references on table "public"."post" to "service_role";

grant select on table "public"."post" to "service_role";

grant trigger on table "public"."post" to "service_role";

grant truncate on table "public"."post" to "service_role";

grant update on table "public"."post" to "service_role";

grant delete on table "public"."subcategory" to "anon";

grant insert on table "public"."subcategory" to "anon";

grant references on table "public"."subcategory" to "anon";

grant select on table "public"."subcategory" to "anon";

grant trigger on table "public"."subcategory" to "anon";

grant truncate on table "public"."subcategory" to "anon";

grant update on table "public"."subcategory" to "anon";

grant delete on table "public"."subcategory" to "authenticated";

grant insert on table "public"."subcategory" to "authenticated";

grant references on table "public"."subcategory" to "authenticated";

grant select on table "public"."subcategory" to "authenticated";

grant trigger on table "public"."subcategory" to "authenticated";

grant truncate on table "public"."subcategory" to "authenticated";

grant update on table "public"."subcategory" to "authenticated";

grant delete on table "public"."subcategory" to "service_role";

grant insert on table "public"."subcategory" to "service_role";

grant references on table "public"."subcategory" to "service_role";

grant select on table "public"."subcategory" to "service_role";

grant trigger on table "public"."subcategory" to "service_role";

grant truncate on table "public"."subcategory" to "service_role";

grant update on table "public"."subcategory" to "service_role";

grant delete on table "staging_digitalocean_supost"."post_staging_import" to "anon";

grant insert on table "staging_digitalocean_supost"."post_staging_import" to "anon";

grant references on table "staging_digitalocean_supost"."post_staging_import" to "anon";

grant select on table "staging_digitalocean_supost"."post_staging_import" to "anon";

grant trigger on table "staging_digitalocean_supost"."post_staging_import" to "anon";

grant truncate on table "staging_digitalocean_supost"."post_staging_import" to "anon";

grant update on table "staging_digitalocean_supost"."post_staging_import" to "anon";

grant delete on table "staging_digitalocean_supost"."post_staging_import" to "authenticated";

grant insert on table "staging_digitalocean_supost"."post_staging_import" to "authenticated";

grant references on table "staging_digitalocean_supost"."post_staging_import" to "authenticated";

grant select on table "staging_digitalocean_supost"."post_staging_import" to "authenticated";

grant trigger on table "staging_digitalocean_supost"."post_staging_import" to "authenticated";

grant truncate on table "staging_digitalocean_supost"."post_staging_import" to "authenticated";

grant update on table "staging_digitalocean_supost"."post_staging_import" to "authenticated";

grant delete on table "staging_digitalocean_supost"."post_staging_import" to "service_role";

grant insert on table "staging_digitalocean_supost"."post_staging_import" to "service_role";

grant references on table "staging_digitalocean_supost"."post_staging_import" to "service_role";

grant select on table "staging_digitalocean_supost"."post_staging_import" to "service_role";

grant trigger on table "staging_digitalocean_supost"."post_staging_import" to "service_role";

grant truncate on table "staging_digitalocean_supost"."post_staging_import" to "service_role";

grant update on table "staging_digitalocean_supost"."post_staging_import" to "service_role";

grant delete on table "staging_digitalocean_supost"."post_staging_import_latest" to "anon";

grant insert on table "staging_digitalocean_supost"."post_staging_import_latest" to "anon";

grant references on table "staging_digitalocean_supost"."post_staging_import_latest" to "anon";

grant select on table "staging_digitalocean_supost"."post_staging_import_latest" to "anon";

grant trigger on table "staging_digitalocean_supost"."post_staging_import_latest" to "anon";

grant truncate on table "staging_digitalocean_supost"."post_staging_import_latest" to "anon";

grant update on table "staging_digitalocean_supost"."post_staging_import_latest" to "anon";

grant delete on table "staging_digitalocean_supost"."post_staging_import_latest" to "authenticated";

grant insert on table "staging_digitalocean_supost"."post_staging_import_latest" to "authenticated";

grant references on table "staging_digitalocean_supost"."post_staging_import_latest" to "authenticated";

grant select on table "staging_digitalocean_supost"."post_staging_import_latest" to "authenticated";

grant trigger on table "staging_digitalocean_supost"."post_staging_import_latest" to "authenticated";

grant truncate on table "staging_digitalocean_supost"."post_staging_import_latest" to "authenticated";

grant update on table "staging_digitalocean_supost"."post_staging_import_latest" to "authenticated";

grant delete on table "staging_digitalocean_supost"."post_staging_import_latest" to "service_role";

grant insert on table "staging_digitalocean_supost"."post_staging_import_latest" to "service_role";

grant references on table "staging_digitalocean_supost"."post_staging_import_latest" to "service_role";

grant select on table "staging_digitalocean_supost"."post_staging_import_latest" to "service_role";

grant trigger on table "staging_digitalocean_supost"."post_staging_import_latest" to "service_role";

grant truncate on table "staging_digitalocean_supost"."post_staging_import_latest" to "service_role";

grant update on table "staging_digitalocean_supost"."post_staging_import_latest" to "service_role";


  create policy "post_select_public"
  on "public"."post"
  as permissive
  for select
  to anon, authenticated
using (true);


CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON app_private.account FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON app_private.message FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON app_private.message_scam_rule FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON app_private.scammer FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON app_private.spammer FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_set_updated_at BEFORE UPDATE ON public.post FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


